### ISSUE TITLE
Controllers - Dashboard - RATED 7/8

### ISSUE THREAD

**Issue by alliedeaver** [Vannasaur/girls-help-desk#12]
- [x] The Dashboard view will be displayed when the URL path is '/:status?'.
- [x] This view will be rendered with the home view, the main layout, the title of 'Dashboard', and whichever user type the user authenticated with.
- [x] If the user is not logged in, they will be automatically redirected away from this view to the Login page instead though the `withAuth` middleware.

If the user is signed in as a `client`:
  * - [ ] We will need to query to the Ticket model where `clientId` matches the `user`.`userId` of the signed in user from the session object, and include User data.
  * - [ ] Only tickets where their user id is present on the 'clientId' field will be included.

If the user is signed in as a `tech`:
  * - [ ] We will need to query to the Ticket model and include User data.
  * - [ ] Tickets where their user id is present on the 'techId' field will be included, as well as any tickets which have the 'status' of 'Open'.

- [ ] If the status parameter is applied to the request, filter the tickets to only those whose status value match the request.
- [ ] All tickets should include `client` and `tech` `firstName` `lastName` `id` and `role` from associated Users.
- [ ] Only tickets which have not been archived should be included in these results.
- [ ] We will need to serialize the data before the view renders.

This view should receive the required values based on context, but also

loggedIn: BOOLEAN
title: STRING
layout: STRING
userType: STRING

**Comment by Vannasaur** [comment]
Updated dashboard, to not include resolved (archived) tickets on all version of dashboard
