### ISSUE TITLE
Helper - determineClass - RATED 2

### ISSUE THREAD

**Issue by alliedeaver** [Vannasaur/girls-help-desk#24]
### Dynamic Classes
Because the Handlebars template files are not responsible for any logic, they are not able to dynamically assess values the way JavaScript can. For this reason, any front-end logic will be handled by our custom helper functions.

* Note: With both the `determineAlignment` function and `determineShowHide` function, you may choose to change the returning string class names based on your CSS Framework.

#### determineAlignment
- [x] The `determineAlignment` function should take in a `log` argument and a `currentUser` argument, and will use these two values to return a string representing the appropriate class determined by a conditional statement. 
- [x] The `log` argument should be the current Log item.
- [x] The `currentUser` argument should be the current authenticated User item.
- [x] The function should return `center-align` if the `log.type` property is either `Created` or `Modified`.
- [x] Otherwise, the function should return `right-align` if the `currentUser.id` strictly equals the `log.userId`.
- [x] The function should return `left-align` if no other conditions match.

* Note: In order to pass two arguments in Handlebars helper methods, simply separate any argument values with a space: `{{helperFuncName argument1 arugment2}}`

#### determineShowHide
- [x] The `determineShowHide` function should take in a `value` argument and return the string representing the appropriate class determined by a conditional statment.
- [x] The `value` argument should be the `log.isHidden` boolean.
- [x] If the `value` is true, this function should return `hidden`.
- [x] Otherwise, the function should return `shown`.

**Comment by codeandlift706** [comment]
DRAFT


module.exports = {
    determineClass: (value) => {
        return value.toString();
    }
}

// Add shown class
// Add hide class

// Left-align
// right-align

//based on what click

const value = //???

switchCaseFun = () => {

    switch (value) {
        case 'hidden':
            return 'hidden'
            break;

        case 'shown':
            return 'shown'
            break;
    }

}

switchCaseBtn.addEventListener('click', switchCaseFun);

**Comment by codeandlift706** [comment]
determineShowHide: (value) => {
if value === log.isHidden ? return "hidden" : return "shown"
}


OR


determineShowHide: (value) => {
    
if (value === log.isHidden) {
return "hidden"; //return the class hidden as a string
} 

if (value !== log.isHidden)
    return "shown"; //return the class shown as a string
}

**Comment by codeandlift706** [comment]
//On each chat log in the ticket
//this goes in ticket.handlebars {{ determineShowHide log.isHidden }}
//NEED TO STYLE IN CSS



    determineShowHide: (value) => {
        return value === true ? "hidden" : "shown";
    },

**Comment by codeandlift706** [comment]
// {{helperFuncName argument1 argument2}}
//this goes in ticket.handlebars {{determineAlignment {isHidden" false, user_id: 1, type: "message"} {id: 1} }}
//the handlebars does the loop - for each currentUser iterate over the log
//NEED TO STYLE IN CSS


    determineAlignment: (log, currentUser) => {
        let log = log.id
        let currentUser = currentUser.id

        if (log.type === "Created") {
            return "center-align";
        }

        if (log.type === "Modified") {
            return "center-align";
        }

        if (currentUser === log.userId) {
            return "right-align";
        }

        else {
            return "left-align";
        }
    }

**Comment by codeandlift706** [comment]
Need to style these in CSS

if "hidden" class
.hidden {
display: none
}


if "shown" class
.shown {
display: block
}

if "center-align" class
.center-align {
text-align: center
}

if "right-align" class
.right-align {
text-align: right
}

if "left-align" class
.left-align {
text-align: left
}
