### ISSUE TITLE
Views - Home - Bottom-half - RATED 6

### ISSUE THREAD

**Issue by Vannasaur** [Vannasaur/girls-help-desk#58]
## Home - Bottom-half
- [x] The bottom portion of the page will have a table showing ticket data depending on the current user type.
- [x] If the user is a `client`, they will see only their own tickets in this table view.
- [x] If the user is a `tech`, they will see any tickets which have the status of `open` or their own tickets.
- [x] If the user is a `tech` and the ticket has a status of `Open`, they will see an additional column with a button they can click to claim.
- [x] The table columns will include `Status`, `Urgency`, `Client`, `Technician`, `Date Created`.
- [x] Each row on this table will be clickable, and will function as a link to take the user to the individual ticket page.
- [x] When there is no ticket data to display as a technician, the table will show "No pending tickets. Check back soon."
- [ ] When there is no ticket data to display as a client, the table will show the same `create new ticket` form which also displays in the drawer.

- [x] The bottom half should match the wireframe.

**Comment by codeandlift706** [comment]
{{#if client}}
{{#each tickets as |ticket|}}
<tr>
    <a href="/ticket/{{ticket.id}}">
        <td class="status-row">{{ticket.status}}</td>
        <td class="urgency-row">{{ticket.urgency}}</td>
        <td class="client-row">{{ticket.client.FirstName}}</td>
        <td class="technician-row">{{ticket.tech.firstName}}</td>
        <td class="created-row">{{ticket.createdAt}}</td>
    </a>
</tr>
{{/each}}
{{else}}
{{#each tickets as |ticket|}}
<tr>
    <a href="/ticket/{{ticket.id}}">
        <td class="claim-row"><button class="claim-ticket-btn">Claim</button></td>
        <td class="status-row">{{ticket.status}}</td>
        <td class="urgency-row">{{ticket.urgency}}</td>
        <td class="client-row">{{ticket.client.FirstName}}</td>
        <td class="technician-row">{{ticket.tech.firstName}}</td>
        <td class="created-row">{{ticket.createdAt}}</td>
    </a>
</tr>
{{/each}}
{{/if}}

**Comment by codeandlift706** [comment]
Each row on this table will be clickable, and will function as a link to take the user to the individual ticket page.

Confirm with Vanna if each individual ticket page will be: /api/ticket/id#
