### ISSUE TITLE
Models - Ticket - Instance Methods - RATED 3

### ISSUE THREAD

**Issue by alliedeaver** [Vannasaur/girls-help-desk#7]
## Instance Methods
- [x] This Ticket model must include a `logChange` instance method to update the Log model to reflect a change to the ticket. Params include `userId` and `oldData`.
  * This method will use the `findDiff` helper method, passing along the changed ticket instance and the previous ticket values.
  * This method will return early if no changes are found.
  * The Log.type will be "Modified"
  * The Log.message will be "findDiff.length changes were made on date by user. iterate the results of findDiff here"
  * The Log.userId field's value will be passed as the argument to this method
  * The Log.ticketId field will be a reference to the instance id

**Comment by codeandlift706** [comment]
branch name: ticketmodel

**Comment by codeandlift706** [comment]
Rough draft:


class Ticket extends Model {


    async logChange(userId, oldData) { //logChange instance method, parameters include userId and oldData
        findDiff = (Ticket, oldData) => { // findDiff helper method, passing the 1. changed ticket instance 2. previous ticket values

            for (let i = 0; i < findDiff.length; i++) {
                if (Ticket.oldData === Ticket[i].value ) {
                    return Ticket.oldData; // This method will return early if no changes are found.
                }

                else if (Ticket.oldData !== Ticket[i].value) {
                    Log.type = "Modified"; // The Log.type will be "Modified"
                    Log.message = "findDiff.length changes were made on date by user. iterate the results of findDiff here"; // The Log.message will be "findDiff.length changes were made on date by user. iterate the results of findDiff here"
                };
            }
        }
    }


}

**Comment by codeandlift706** [comment]
class Ticket extends Model {



    async logChange(userId, oldData) { //logChange instance method, parameters include userId and oldData
        const differences = await findDiff(this, oldData); //find difference between current ticket value and previous ticket values
        if (differences === 0) {
            return;
        } else ({
            const log = await Log.create({
                type = "Modified",
                message = `${diffs.length} changes were made on ${date} by ${user}. ${diffs.join(this, oldData)}`, //combine previous updates + new updates
                userId,
                ticketId: this.id,
            })
        })
    }



    }

**Comment by codeandlift706** [comment]
class Ticket extends Model {    




async logChange(userId, oldData) { //logChange instance method, parameters include userId and oldData
        const differences = await findDiff(this, oldData); //find difference between current ticket value and previous ticket values
        if (differences.length === 0) {
            return;
        }
            const log = await Log.create({
                type: "Modified",
                message: `${differences.length} changes were made on ${new Date()} by user ${userId}. ${diffs.join(", ")}`, //combine previous updates + new updates separated by commas
                userId,
                ticketId: this.id,
            });
            await log.save();
        }



}

**Comment by codeandlift706** [comment]
class Ticket extends Model {

    async logChange(userId, oldData) { //logChange instance method, parameters include userId and oldData
        const differences = await findDiff(this, oldData); //find difference between current ticket value and previous ticket values
        if (differences.length === 0) {
            return;
        }
        await log.create({
            type: "Modified",
            message: `${differences.length} changes were made on ${new Date()} by user ${userId}. ${diffs.join(", ")}`, //combine previous updates + new updates separated by commas
            userId,
            ticketId: this.id,
        });
        await log.save();
    }
}
